# Generated by Django 4.2.1 on 2023-06-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kidmeet_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_column='city', max_length=128)),
                ('street', models.CharField(db_column='street', max_length=128)),
                ('building_number', models.CharField(blank=True, db_column='building_number', max_length=20, null=True)),
                ('floor_number', models.IntegerField(blank=True, db_column='floor_number', null=True)),
                ('apartment_number', models.IntegerField(blank=True, db_column='apartment_number', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='child_name', max_length=128)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='event_title', max_length=128)),
                ('description', models.TextField(db_column='description', null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, db_column='start_event')),
                ('end_time', models.DateTimeField(auto_now_add=True, db_column='end_event')),
                ('place', models.CharField(blank=True, db_column='event_place', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='interest_name', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('birth_year', models.IntegerField(db_column='birth_year', validators=[kidmeet_app.models.validate_birth_date])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(db_column='weekly_schedule', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type_activity', models.CharField(db_column='type_activity', max_length=128)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.child')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergarten', models.CharField(blank=True, db_column='child_kindergarten', max_length=128, null=True)),
                ('school', models.CharField(blank=True, db_column='child_school', max_length=128, null=True)),
                ('classroom', models.CharField(blank=True, db_column='child_classroom', max_length=128, null=True)),
                ('child1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_child1', to='kidmeet_app.child')),
                ('child2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_child2', to='kidmeet_app.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.child')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.interests')),
            ],
        ),
        migrations.CreateModel(
            name='ChildEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.child')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidmeet_app.event')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='events',
            field=models.ManyToManyField(through='kidmeet_app.ChildEvent', to='kidmeet_app.event'),
        ),
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.ManyToManyField(through='kidmeet_app.ChildInterests', to='kidmeet_app.interests'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
