# Generated by Django 4.2.1 on 2023-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidmeet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, db_column='location', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_column='title', max_length=128),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='classroom',
            field=models.CharField(blank=True, db_column='classroom', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='kindergarten',
            field=models.CharField(blank=True, db_column='kindergarten', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='school',
            field=models.CharField(blank=True, db_column='school', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(db_column='name', max_length=128),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='child',
            table='children',
        ),
        migrations.AlterModelTable(
            name='childevent',
            table='child_event',
        ),
        migrations.AlterModelTable(
            name='childinterests',
            table='children_interests',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='friendship',
            table='friendship',
        ),
        migrations.AlterModelTable(
            name='interests',
            table='interests',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='user_details',
        ),
    ]
