# Generated by Django 4.2.1 on 2023-07-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidmeet_app', '0009_schedule_end_time_schedule_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
