# Generated by Django 4.2.1 on 2023-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidmeet_app', '0010_delete_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='classroom',
            field=models.CharField(blank=True, db_column='classroom', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='kindergarten',
            field=models.CharField(blank=True, db_column='kindergarten', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.CharField(blank=True, db_column='school', max_length=128, null=True),
        ),
    ]
