# Generated by Django 4.2.1 on 2023-09-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kidmeet_app', '0011_child_classroom_child_kindergarten_child_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='events',
            field=models.ManyToManyField(related_name='children', through='kidmeet_app.ChildEvent', to='kidmeet_app.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
